### ISSUE TITLE
How to add this to the ingress if we're using an nginx ingress controller

### ISSUE THREAD

**Issue by DrissiReda** [Folcky/vault_nginx#1]
So I'm using an nginx controller:

This is my vault-ingress file

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: vault-ingress
spec:
  rules:
  - http:
      paths:
      - path: /vault/?(.*)
        backend:
          serviceName: vault
          servicePort: 8200

```
How can I insert nginx config code directly inside the ingress if it is even at all possible
